### PR TITLE
RFC 0019-new-kademlia-routing-logic

### PR DESCRIPTION
**Pull request by afck**
Changes needed for the new routing mechanism as per the RFC:
https://github.com/maidsafe/rfcs/blob/master/active/0019-new-kademlia-routing-logic/0019-new-kademlia-routing-logic.md

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/kademlia_routing_table/20)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/maidsafe/kademlia_routing_table/20#-K9H4DcLnTLD9Z3qGSyt:-K9H4DcLnTLD9Z3qGSyu:1200942208) (no related file):*
This is an excellent PR, albeit a little on the large side :-) Could we please run clippy (pedantic) on this as there are a couple of small issues it will pick up I think. 

---

*[src/lib.rs, line 316 \[r6\]](https://reviewable.io:443/reviews/maidsafe/kademlia_routing_table/20#-K9H4jS6n8zQwiXuVrKj:-K9H4jS6n8zQwiXuVrKk:1930090340) ([raw file](https://github.com/maidsafe/kademlia_routing_table/blob/baeef357afe954b26f877c61a12fec8c835ab047/src/lib.rs#L316)):*
Yes this does make more sense. 

---

*[src/lib.rs, line 356 \[r6\]](https://reviewable.io:443/reviews/maidsafe/kademlia_routing_table/20#-K9H5BlYs1NKMDnK9wwH:-K9H5BlYs1NKMDnK9wwI:1981675732) ([raw file](https://github.com/maidsafe/kademlia_routing_table/blob/baeef357afe954b26f877c61a12fec8c835ab047/src/lib.rs#L356)):*
I wonder if it is more rust container like to call this `remove_node` ? or `remove`

---

*[src/lib.rs, line 456 \[r6\]](https://reviewable.io:443/reviews/maidsafe/kademlia_routing_table/20#-K9H5XJJzB2UUQRxG522:-K9H5XJJzB2UUQRxG523:682155934) ([raw file](https://github.com/maidsafe/kademlia_routing_table/blob/baeef357afe954b26f877c61a12fec8c835ab047/src/lib.rs#L456)):*
Should we confirm `is_sorted()` here ? Or ensure it cannot be not sorted perhaps. I mean are we happy the RT is always sorted and any other actions are done on clones?

---

*[src/lib.rs, line 517 \[r6\]](https://reviewable.io:443/reviews/maidsafe/kademlia_routing_table/20#-K9H3xS4Eh0pubFZAA_3:-K9H3xS4Eh0pubFZAA_4:-419064006) ([raw file](https://github.com/maidsafe/kademlia_routing_table/blob/baeef357afe954b26f877c61a12fec8c835ab047/src/lib.rs#L517)):*
prob better `for node in &self.nodes { ` 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/kademlia_routing_table/20)*

**Comment by afck** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/lib.rs, line 356 \[r6\]](https://reviewable.io:443/reviews/maidsafe/kademlia_routing_table/20#-K9H5BlYs1NKMDnK9wwH:-K9HU6DAwXK229ehZza1:-499146009) ([raw file](https://github.com/maidsafe/kademlia_routing_table/blob/baeef357afe954b26f877c61a12fec8c835ab047/src/lib.rs#L356)):*
Done.

---

*[src/lib.rs, line 456 \[r6\]](https://reviewable.io:443/reviews/maidsafe/kademlia_routing_table/20#-K9H5XJJzB2UUQRxG522:-K9HUDagpXPL4isD80zG:-499146009) ([raw file](https://github.com/maidsafe/kademlia_routing_table/blob/baeef357afe954b26f877c61a12fec8c835ab047/src/lib.rs#L456)):*
Done.

---

*[src/lib.rs, line 517 \[r6\]](https://reviewable.io:443/reviews/maidsafe/kademlia_routing_table/20#-K9H3xS4Eh0pubFZAA_3:-K9HUE_FJBwyvqvxNPu_:-495237053) ([raw file](https://github.com/maidsafe/kademlia_routing_table/blob/baeef357afe954b26f877c61a12fec8c835ab047/src/lib.rs#L517)):*
Done.
This was exactly the one point that clippy found. :+1: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/kademlia_routing_table/20)*

**Comment by dirvine** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/kademlia_routing_table/20)*

**Pull request merged**
