### PR TITLE
Make constants usize, change BUCKET_SIZE and add a test for the constraints.

### PR DESCRIPTION
**Pull request by afck**

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Looks good, although it is not clear why we would have a getter for a const and also the const itself public? 
If possible it would also be good to have clippy run clean on the repo. In particular the floating point conversions may be a potential for data loss if there was no constraints on const sizes perhaps?

**Comment by afck** [comment]
I marked all the getters as `Deprecated` but left them in the code for now, so that the next crate version doesn't break the libraries that use them. Once we've updated these libraries (probably only routing?), I will remove the deprecated methods.

I ran clippy: It doesn't complain to me. :+1: 

And the current floating point logic in `dynamic_quorum_size` is wrong anyway: It sometimes returns 0, and doesn't make sure that the returned value is always greater than half the number of nodes. And it doesn't add itself to the nodes. And there's no reason to use floating point at all. I changed that.

**Comment by dirvine** [comment]
:+1:

**Comment by afck** [comment]
As discussed, some of the changes are going to be backwards-incompatible anyway, so I removed the deprecated methods.

**Pull request merged**
